import type { QuestionDef, SectionDef } from "./types";

export const QUESTIONS: Record<string, QuestionDef> = {
  "S1": {
    key: "S1",
    text: "Bạn đang học tiếng Đức vì mục tiêu gì?",
    type: "radio",
    options: ["Thi chứng chỉ B1/B2", "XKLĐ — Xuất khẩu lao động", "Du học / học nghề tại Đức, Áo, Thụy Sĩ", "Làm việc tại công ty Đức ở Việt Nam", "Sở thích cá nhân", "Khác (ghi rõ)"],
    hasOther: true,
  },
  "S2": {
    key: "S2",
    text: "Bạn thuộc nhóm nào?",
    type: "radio",
    options: ["Học sinh / Sinh viên", "Đã đi XKLĐ", "Đang chuẩn bị đi XKLĐ", "Người đi làm tự học", "Khác (ghi rõ)"],
    hasOther: true,
  },
  "S3": {
    key: "S3",
    text: "Trình độ tiếng Đức hiện tại của bạn là gì?",
    type: "radio",
    options: ["Chưa biết gì", "A1", "A2", "B1", "B2+"],
  },
  "S4": {
    key: "S4",
    text: "Bạn có deadline thi chứng chỉ cụ thể không?",
    type: "radio",
    options: ["Có", "Không"],
    conditional: {
      triggerValue: "Có",
      label: "Thời hạn cụ thể là khi nào? Thi chứng chỉ gì?",
      placeholder: "VD: Tháng 8/2025 — Goethe B1",
    },
  },
  "B1": {
    key: "B1",
    text: "Kể lại hành trình học tiếng Đức của bạn từ đầu đến nay?",
    type: "textarea",
    helper: "Câu mở — để user tự kể, đừng ngắt lời",
  },
  "B2": {
    key: "B2",
    text: "Hiện bạn đang học theo hình thức nào?",
    type: "checkbox",
    options: ["Trung tâm ngoại ngữ", "App / website tự học", "Gia sư 1-1", "YouTube / tài liệu miễn phí", "Chưa học", "Khác (ghi rõ)"],
    hasOther: true,
  },
  "B3": {
    key: "B3",
    text: "Một tuần bạn dành bao nhiêu giờ để học? Có đều đặn không?",
    type: "radio",
    options: ["Dưới 3 giờ / tuần", "3 – 5 giờ / tuần", "5 – 10 giờ / tuần", "Trên 10 giờ / tuần"],
  },
  "B4": {
    key: "B4",
    text: "Bạn thường học vào thời điểm nào trong ngày? Ở đâu?",
    type: "checkbox",
    helper: "Quan trọng để thiết kế mobile UX và notification timing",
    options: ["Sáng sớm (5–8h)", "Buổi trưa (11–13h)", "Buổi chiều (13–17h)", "Buổi tối (17–22h)", "Linh hoạt / tranh thủ lúc rảnh"],
  },
  "B5": {
    key: "B5",
    text: "Bạn thường học trên thiết bị nào?",
    type: "radio",
    options: ["Điện thoại là chính", "Laptop / PC là chính", "Tablet là chính", "Cả điện thoại và laptop tuỳ lúc"],
  },
  "B6": {
    key: "B6",
    text: "Bạn thích học theo kiểu nào nhất?",
    type: "radio",
    options: ["Video bài giảng", "Bài tập tương tác", "Luyện đề / luyện thi", "Live class với giảng viên", "Tự đọc tài liệu", "Khác (ghi rõ)"],
    hasOther: true,
  },
  "B7": {
    key: "B7",
    text: "Bạn thích lộ trình học cố định (A1→B1) hay tự chọn theo mục tiêu?",
    type: "radio",
    options: ["Lộ trình cố định A1→B1 (có cấu trúc rõ)", "Tự chọn theo mục tiêu cá nhân", "Tự do chọn bài theo nhu cầu từng ngày"],
  },
  "B8": {
    key: "B8",
    text: "Bạn có cần hệ thống nhắc nhở hoặc kỷ luật học không? Tại sao?",
    type: "radio",
    options: ["Có — rất cần, tôi hay quên", "Có — nếu notification không spam", "Không cần — tôi tự giác"],
  },
  "P1": {
    key: "P1",
    text: "Phần nào của tiếng Đức khiến bạn khó khăn nhất?",
    type: "checkbox",
    options: ["Nói / Phát âm", "Ngữ pháp (Artikel, Kasus, cấu trúc câu)", "Nghe hiểu", "Từ vựng chuyên ngành", "Viết / Làm bài thi", "Thiếu môi trường thực hành", "Khác (ghi rõ)"],
    hasOther: true,
    maxSelect: 3,
  },
  "P2": {
    key: "P2",
    text: "Bạn từng \"bỏ cuộc\" hoặc mất động lực học chưa? Lúc đó xảy ra chuyện gì?",
    type: "radio",
    options: ["Gặp ngữ pháp quá khó", "Không thấy tiến bộ rõ ràng", "Mất deadline / áp lực công việc", "Nội dung nhàm chán", "Không có bạn học cùng", "Chưa từng bỏ cuộc", "Khác (ghi rõ)"],
    hasOther: true,
    maxSelect: 3,
  },
  "P3": {
    key: "P3",
    text: "Điều gì khiến bạn thấy cách học hiện tại chưa hiệu quả?",
    type: "textarea",
  },
  "P4": {
    key: "P4",
    text: "Bạn đã dùng những app/website nào để học? Điều gì bạn không hài lòng?",
    type: "textarea",
  },
  "P5": {
    key: "P5",
    text: "Nếu từng học tại trung tâm: điều gì bạn thấy thiếu hoặc không đáng tiền?",
    type: "textarea",
  },
  "P6": {
    key: "P6",
    text: "Bạn có thể kể 1 tình huống thực tế bạn cần dùng tiếng Đức mà chưa làm được?",
    type: "textarea",
  },
  "P7": {
    key: "P7",
    text: "Bạn gặp khó khăn gì khi đọc chữ hoặc nghe audio trên app hiện tại?",
    type: "textarea",
  },
  "P8": {
    key: "P8",
    text: "Bạn thấy tự học online có đáp ứng được so với học trực tiếp không? Tại sao?",
    type: "radio",
    options: ["Có — online tiện hơn và hiệu quả hơn", "Phần nào — tùy kỹ năng", "Không — vẫn thích học trực tiếp hơn"],
  },
  "P9": {
    key: "P9",
    text: "Nếu không đạt chứng chỉ đúng hạn, hậu quả với bạn là gì?",
    type: "textarea",
  },
  "P10": {
    key: "P10",
    text: "Điều gì bạn thấy còn thiếu ở TẤT CẢ các giải pháp bạn đã thử?",
    type: "textarea",
  },
  "K1": {
    key: "K1",
    text: "Với bạn, \"học tiếng Đức thành công\" nghĩa là gì cụ thể?",
    type: "textarea",
  },
  "K2": {
    key: "K2",
    text: "Khóa học tiếng Đức online phải có những yếu tố nào bạn mới dùng? (chọn nhiều)",
    type: "checkbox",
    options: ["Video bài giảng", "Bài nghe thực tế (hội thoại, âm thanh thật)", "AI chatbot luyện nói hội thoại 24/7", "Luyện đề thi (Goethe, ÖSD, TELC)", "Progress tracking rõ ràng", "Chứng nhận sau khi hoàn thành khóa", "Feedback ngữ pháp tức thì", "Community / nhóm học cùng", "Khác (ghi rõ)"],
    hasOther: true,
  },
  "K3": {
    key: "K3",
    text: "Bạn có muốn AI cho phép luyện nói hội thoại 24/7 không? Bạn sẽ dùng trong tình huống nào?",
    type: "radio",
    options: ["Có — rất cần, luyện nói là điểm yếu nhất", "Có — nếu AI phát âm chuẩn và có feedback ngay", "Không chắc — tôi thích nói với người thật hơn", "Không — không phải ưu tiên"],
  },
  "K4": {
    key: "K4",
    text: "Khi gặp ngữ pháp khó, bạn muốn được hỗ trợ theo cách nào?",
    type: "radio",
    options: ["Chat với AI giải thích ngay", "Hỏi giáo viên thật", "Xem cộng đồng học viên giải đáp", "Tự tìm kiếm trên Google / YouTube"],
  },
  "K5": {
    key: "K5",
    text: "Bạn muốn giao diện LMS hiển thị ngôn ngữ như thế nào?",
    type: "radio",
    options: ["Song ngữ Tiếng Việt – Tiếng Đức", "Tiếng Việt là chính + phụ đề tiếng Đức", "Chủ yếu tiếng Đức (dành cho người có nền tảng)"],
  },
  "K6": {
    key: "K6",
    text: "Bạn có cần tính năng học offline không? (học khi không có mạng)",
    type: "radio",
    options: ["Có — rất cần thiết", "Không cần — tôi luôn có mạng", "Không quan trọng với tôi"],
  },
  "K7": {
    key: "K7",
    text: "Ngoài học tiếng, bạn có cần hỗ trợ thêm gì không?",
    type: "checkbox",
    options: ["Chuẩn bị hồ sơ XKLĐ / du học", "Luyện phỏng vấn tiếng Đức", "Kết nối với agency / trung tâm uy tín", "Không cần gì thêm"],
  },
  "K8": {
    key: "K8",
    text: "[Concept test] Nếu có nền tảng: lộ trình A1→B1 rõ ràng, luyện đề sát thi thật, cam kết đầu ra — điều gì hấp dẫn nhất? Điều gì khiến bạn KHÔNG tin tưởng?",
    type: "textarea",
  },
  "U1": {
    key: "U1",
    text: "Ấn tượng đầu tiên khi nhìn trang chủ — bạn nghĩ đây là app gì?",
    type: "textarea",
  },
  "U2": {
    key: "U2",
    text: "Các nút/menu có rõ nghĩa và dễ tìm không? Phần nào gây bối rối?",
    type: "textarea",
  },
  "U3": {
    key: "U3",
    text: "Luồng từ đăng ký → chọn khóa → bắt đầu học có dễ hiểu không?",
    type: "scale",
    scaleMin: 1,
    scaleMax: 5,
    scaleMinLabel: "Rất khó hiểu",
    scaleMaxLabel: "Rất dễ hiểu",
  },
  "U4": {
    key: "U4",
    text: "Có phần nào khiến bạn phân tâm, thấy thừa hoặc không cần thiết?",
    type: "textarea",
  },
  "U5": {
    key: "U5",
    text: "Bạn thích phong cách giao diện nào hơn?",
    type: "radio",
    options: ["Chuyên nghiệp / hàn lâm (Coursera style)", "Tươi vui / gamification (Duolingo style)", "Trung dung — vừa dễ nhìn vừa nghiêm túc"],
  },
  "U6": {
    key: "U6",
    text: "Khi gặp lỗi (nộp bài không được, video không load), bạn mong hệ thống phản hồi ra sao?",
    type: "textarea",
  },
  "U7": {
    key: "U7",
    text: "Bạn muốn kênh hỗ trợ nào khi cần giúp đỡ?",
    type: "checkbox",
    options: ["Zalo", "In-app chat", "Email", "Hotline", "FAQ tự phục vụ"],
  },
  "T1": {
    key: "T1",
    text: "Bạn đã từng chi bao nhiêu tiền cho việc học tiếng Đức? Dùng vào đâu?",
    type: "radio",
    options: ["Chưa chi gì", "Dưới 500.000 VNĐ", "500.000 – 2.000.000 VNĐ", "2.000.000 – 5.000.000 VNĐ", "Trên 5.000.000 VNĐ"],
  },
  "T2": {
    key: "T2",
    text: "Bạn sẵn sàng trả bao nhiêu cho một khóa học 3 tháng đảm bảo đầu ra B1?",
    type: "number",
    numberUnit: "nghìn VNĐ / khóa",
    numberPlaceholder: "VD: 700",
  },
  "T3": {
    key: "T3",
    text: "Bạn thích mô hình thanh toán nào hơn?",
    type: "radio",
    options: ["Trả một lần theo khóa", "Subscription hàng tháng", "Trả theo kết quả (chỉ trả nếu đỗ chứng chỉ)"],
  },
  "T4": {
    key: "T4",
    text: "Điều gì ảnh hưởng nhiều nhất đến quyết định đăng ký của bạn?",
    type: "checkbox",
    options: ["Cam kết đầu ra / đảm bảo đỗ B1", "Review và testimonial từ người đã học", "Giá cả hợp lý / có ưu đãi", "Uy tín của giảng viên / trung tâm", "Partnership với agency XKLĐ uy tín", "Có thể dùng thử miễn phí trước", "Khác (ghi rõ)"],
    hasOther: true,
  },
  "T5": {
    key: "T5",
    text: "Bạn có tin tưởng khi nhập thông tin thanh toán vào nền tảng học online không? Bạn muốn thấy gì để tăng tin tưởng?",
    type: "checkbox",
    options: ["Video testimonial từ học viên đã đỗ", "Chính sách hoàn tiền nếu không đạt", "Demo AI luyện nói miễn phí trước khi đăng ký", "Partnership với trung tâm / agency uy tín", "Hỗ trợ thanh toán Zalo Pay / MoMo", "Khác (ghi rõ)"],
    hasOther: true,
    maxSelect: 3,
  },
  "T6": {
    key: "T6",
    text: "Xác suất bạn giới thiệu LMS này cho người khác là bao nhiêu? (NPS proxy)",
    type: "scale",
    scaleMin: 0,
    scaleMax: 10,
    scaleMinLabel: "Chắc chắn không",
    scaleMaxLabel: "Chắc chắn giới thiệu",
  },
  "T7": {
    key: "T7",
    text: "Nếu bạn là người tạo ra sản phẩm này, bạn sẽ làm gì khác đi?",
    type: "textarea",
  },
  "GEN1": {
    key: "GEN1",
    text: "Vai trò chính thức của bạn là gì?",
    type: "radio",
    options: ["Giáo viên / Giảng viên tiếng Đức", "Phụ huynh học viên", "Nhân viên tư vấn giáo dục / du học", "Nhân viên lãnh sự quán / cơ quan văn hoá Đức", "Khác (ghi rõ)"],
    hasOther: true,
  },
  "GEN2": {
    key: "GEN2",
    text: "Bạn gắn bó với lĩnh vực giáo dục tiếng Đức bao nhiêu năm?",
    type: "radio",
    options: ["Dưới 1 năm", "1 – 3 năm", "3 – 5 năm", "Trên 5 năm"],
  },
  "GEN3": {
    key: "GEN3",
    text: "Tổ chức / đơn vị bạn đang làm việc hoặc liên kết",
    type: "text",
    helper: "Tên trường, trung tâm, công ty, hoặc cơ quan",
  },
  "GEN4": {
    key: "GEN4",
    text: "Bạn tiếp xúc hoặc làm việc với bao nhiêu học viên tiếng Đức mỗi tháng?",
    type: "radio",
    options: ["Dưới 10 người", "10 – 50 người", "50 – 200 người", "Trên 200 người", "Không trực tiếp tiếp xúc học viên"],
  },
  "GEN5": {
    key: "GEN5",
    text: "Bạn đã từng sử dụng hoặc giới thiệu LMS / nền tảng học tiếng Đức trực tuyến nào chưa?",
    type: "radio",
    options: ["Có — đang dùng thường xuyên", "Có — đã thử nhưng không dùng nữa", "Chưa bao giờ dùng"],
    conditional: {
      triggerValue: "Có — đang dùng thường xuyên",
      label: "GEN6 — Đó là nền tảng nào? Ấn tượng chung của bạn?",
      placeholder: "Tên nền tảng và nhận xét...",
    },
  },
  "TCH-A1": {
    key: "TCH-A1",
    text: "Bạn đang dạy tiếng Đức ở cấp độ nào?",
    type: "checkbox",
    options: ["A1", "A2", "B1", "B2", "C1 / C2", "Tất cả cấp độ"],
  },
  "TCH-A2": {
    key: "TCH-A2",
    text: "Hình thức dạy học chính của bạn hiện tại?",
    type: "checkbox",
    options: ["Lớp học trực tiếp tại trung tâm / trường", "Dạy online qua Zoom / Google Meet", "Gia sư 1-1 tại nhà hoặc online", "Kết hợp offline và online (blended)"],
  },
  "TCH-A3": {
    key: "TCH-A3",
    text: "Học viên chủ yếu của bạn thuộc nhóm nào?",
    type: "checkbox",
    options: ["Học sinh phổ thông", "Sinh viên đại học", "Người chuẩn bị đi XKLĐ", "Người đi làm tự học", "Người chuẩn bị du học / định cư", "Doanh nhân / chuyên gia"],
  },
  "TCH-A4": {
    key: "TCH-A4",
    text: "Khó khăn lớn nhất bạn gặp khi dạy tiếng Đức hiện tại?",
    type: "checkbox",
    options: ["Thiếu tài liệu học sát thực tế", "Học viên mất động lực giữa chừng", "Không có công cụ theo dõi tiến độ học viên", "Khó cá nhân hoá lộ trình cho từng học viên", "Thiếu bài tập luyện nói / phát âm hiệu quả", "Học viên không có nơi thực hành ngoài giờ học", "Khác (ghi rõ)"],
    hasOther: true,
  },
  "TCH-B1": {
    key: "TCH-B1",
    text: "Nếu có LMS tiếng Đức, bạn muốn dùng nó như thế nào trong giảng dạy?",
    type: "checkbox",
    options: ["Giao bài tập về nhà và theo dõi kết quả", "Dùng làm tài liệu bổ trợ cho lớp offline", "Chuyển toàn bộ lớp học sang online qua LMS", "Giới thiệu cho học viên tự học ngoài giờ", "Dùng bank câu hỏi / đề thi để ra đề", "Khác (ghi rõ)"],
    hasOther: true,
    maxSelect: 3,
  },
  "TCH-B2": {
    key: "TCH-B2",
    text: "Tính năng nào quan trọng nhất với bạn với tư cách giáo viên?",
    type: "checkbox",
    options: ["Dashboard theo dõi tiến độ từng học viên", "Công cụ tạo bài tập / đề kiểm tra", "Giao bài và chấm điểm tự động", "Kho nội dung chuẩn theo khung CEFR", "Báo cáo kết quả học tập cho phụ huynh", "Tích hợp với lịch dạy / lớp học của tôi", "Tính năng nhận xét / feedback cho học viên"],
  },
  "TCH-B3": {
    key: "TCH-B3",
    text: "Bạn có muốn đóng góp nội dung (bài giảng, bài tập) vào LMS và nhận compensation không?",
    type: "radio",
    options: ["Có — rất quan tâm", "Có — nếu có cơ chế rõ ràng", "Không — chỉ muốn dùng, không muốn tạo nội dung", "Cần thêm thông tin trước khi quyết định"],
    maxSelect: 3,
  },
  "TCH-B4": {
    key: "TCH-B4",
    text: "Điều gì có thể khiến bạn KHÔNG giới thiệu LMS này cho học viên?",
    type: "textarea",
  },
  "TCH-B5": {
    key: "TCH-B5",
    text: "Bạn sẵn sàng trả / hoặc nhận mức phí như thế nào?",
    type: "radio",
    options: ["Miễn phí hoàn toàn mới dùng", "Trả nếu có tài khoản giáo viên riêng với đầy đủ tính năng", "Tổ chức / trung tâm tôi trả (B2B)", "Nhận commission khi giới thiệu học viên đăng ký", "Khác (ghi rõ)"],
    hasOther: true,
  },
  "PAR-A1": {
    key: "PAR-A1",
    text: "Con / học viên bạn quan tâm đang ở độ tuổi nào?",
    type: "radio",
    options: ["Dưới 12 tuổi", "12 – 15 tuổi", "15 – 18 tuổi", "18 – 22 tuổi (sinh viên)", "Trên 22 tuổi"],
  },
  "PAR-A2": {
    key: "PAR-A2",
    text: "Mục tiêu chính khi cho con học tiếng Đức là gì?",
    type: "radio",
    options: ["Chuẩn bị hồ sơ du học Đức / Áo / Thụy Sĩ", "Tăng cơ hội nghề nghiệp trong tương lai", "Học vì bản thân con muốn", "Chuẩn bị đi XKLĐ sau này", "Yêu cầu của trường / chương trình đang học", "Khác (ghi rõ)"],
    hasOther: true,
  },
  "PAR-B1": {
    key: "PAR-B1",
    text: "Lo ngại lớn nhất của bạn khi cho con học online là gì?",
    type: "checkbox",
    options: ["Con không tự giác, dễ bị xao nhãng", "Không biết con có thực sự học hay không", "Chất lượng dạy kém hơn học trực tiếp", "Con dùng thiết bị vào việc khác", "Không có người kèm cặp trực tiếp khi cần", "Bảo mật thông tin cá nhân của con", "Khác (ghi rõ)"],
    hasOther: true,
    maxSelect: 3,
  },
  "PAR-B4": {
    key: "PAR-B4",
    text: "Ngân sách sẵn sàng đầu tư cho việc học tiếng Đức của con mỗi tháng?",
    type: "radio",
    options: ["Dưới 500.000 VNĐ / tháng", "500.000 – 1.000.000 VNĐ / tháng", "1.000.000 – 2.000.000 VNĐ / tháng", "Trên 2.000.000 VNĐ / tháng", "Trả một lần theo khóa, không theo tháng"],
  },
  "PAR-B5": {
    key: "PAR-B5",
    text: "Điều gì sẽ khiến bạn chắc chắn giới thiệu LMS này cho phụ huynh khác?",
    type: "textarea",
  },
  "CNS-A2": {
    key: "CNS-A2",
    text: "Trong tổng số học viên bạn tư vấn, tiếng Đức chiếm khoảng bao nhiêu phần trăm?",
    type: "radio",
    options: ["Dưới 10%", "10 – 30%", "30 – 60%", "Trên 60%", "Gần như 100% (chuyên tiếng Đức)"],
  },
  "CNS-B2": {
    key: "CNS-B2",
    text: "Bạn có muốn tham gia chương trình partnership (affiliate / referral) không?",
    type: "radio",
    options: ["Có — nếu commission hợp lý (&gt;10%/đơn hàng)", "Có — nếu có dashboard theo dõi học viên tôi giới thiệu", "Chỉ quan tâm nếu LMS thực sự chất lượng", "Không — tránh conflict of interest với học viên"],
  },
  "CNS-B3": {
    key: "CNS-B3",
    text: "Học viên nào khó tìm được giải pháp học tiếng Đức phù hợp nhất hiện nay?",
    type: "textarea",
  },
  "CNS-B4": {
    key: "CNS-B4",
    text: "Nếu LMS có \"Counselor Portal\" — theo dõi tất cả học viên mình giới thiệu và nhận báo cáo tiến độ — bạn có dùng không?",
    type: "radio",
    options: ["Có — đây chính xác là thứ tôi cần", "Có — nếu không tốn thêm phí", "Cần xem demo trước", "Không cần thiết với workflow của tôi"],
  },
  "CLT-A1": {
    key: "CLT-A1",
    text: "Bạn đang làm việc tại tổ chức nào?",
    type: "radio",
    options: ["Đại sứ quán / Tổng Lãnh sự quán CHLB Đức", "Goethe-Institut Việt Nam", "DAAD (Deutscher Akademischer Austauschdienst)", "Phòng Thương mại Đức (AHK Vietnam)", "Tổ chức văn hoá / học thuật Đức khác", "Khác (ghi rõ)"],
    hasOther: true,
  },
  "CLT-A4": {
    key: "CLT-A4",
    text: "Nhận xét về trình độ tiếng Đức thực tế của người học Việt Nam so với chứng chỉ họ nộp?",
    type: "radio",
    options: ["Thường khớp — chứng chỉ phản ánh đúng năng lực", "Thường thấp hơn chứng chỉ — đặc biệt phần nói và nghe", "Rất thấp hơn — chứng chỉ không đáng tin cậy", "Không đủ dữ liệu để nhận xét"],
  },
  "CLT-B1": {
    key: "CLT-B1",
    text: "Điểm yếu lớn nhất của các khóa học / LMS tiếng Đức hiện có tại Việt Nam?",
    type: "checkbox",
    options: ["Không đạt chuẩn CEFR thực sự dù quảng cáo là đạt", "Thiếu luyện nói và phát âm chuẩn", "Nội dung không cập nhật với đề thi mới nhất", "Thiếu yếu tố văn hoá Đức trong nội dung", "Giáo viên không được đào tạo theo phương pháp chuẩn", "Không có cơ chế kiểm tra độc lập / proctoring", "Khác (ghi rõ)"],
    hasOther: true,
    maxSelect: 3,
  },
  "CLT-B4": {
    key: "CLT-B4",
    text: "Những tình huống giao tiếp nào người Việt học tiếng Đức thường yếu nhất khi phỏng vấn hoặc tiếp xúc thực tế?",
    type: "textarea",
  },
  "CLT-B5": {
    key: "CLT-B5",
    text: "Nếu LMS được xây dựng đúng chuẩn, bạn có sẵn sàng chia sẻ thông tin đến cộng đồng người học qua kênh truyền thông của tổ chức không?",
    type: "radio",
    options: ["Sẵn sàng — nếu đáp ứng tiêu chí chất lượng", "Cần qua quy trình review và approval chính thức", "Không thể — tổ chức không endorse sản phẩm thương mại", "Có thể đề xuất lên cấp trên xem xét"],
  },
};

export const SECTIONS: Record<string, Record<string, SectionDef>> = {
  lrn: {
    "S": {
      title: "S · Screening",
      subtitle: "4 câu",
      color: "#0F6E56",
      bg: "#E1F5EE",
      keys: ["S1", "S2", "S3", "S4"],
    },
    "B": {
      title: "B · Background & Context",
      subtitle: "8 câu",
      color: "#0F6E56",
      bg: "#E1F5EE",
      keys: ["B1", "B2", "B3", "B4", "B5", "B6", "B7", "B8"],
    },
    "P": {
      title: "P · Pain Points",
      subtitle: "10 câu (phần quan trọng nhất)",
      color: "#993C1D",
      bg: "#FAECE7",
      keys: ["P1", "P2", "P3", "P4", "P5", "P6", "P7", "P8", "P9", "P10"],
    },
    "K": {
      title: "K · Kỳ vọng sản phẩm",
      subtitle: "8 câu",
      color: "#534AB7",
      bg: "#EEEDFE",
      keys: ["K1", "K2", "K3", "K4", "K5", "K6", "K7", "K8"],
    },
    "U": {
      title: "U · UX & Thiết kế",
      subtitle: "7 câu (dùng khi có prototype)",
      color: "#854F0B",
      bg: "#FAEEDA",
      keys: ["U1", "U2", "U3", "U4", "U5", "U6", "U7"],
    },
    "T": {
      title: "T · Trust & Closing",
      subtitle: "7 câu",
      color: "#185FA5",
      bg: "#E6F1FB",
      keys: ["T1", "T2", "T3", "T4", "T5", "T6", "T7"],
    },
  },
  gen: {
    "GEN": {
      title: "GEN · Screening chung",
      subtitle: "6 câu",
      color: "#534AB7",
      bg: "#EEEDFE",
      keys: ["GEN1", "GEN2", "GEN3", "GEN4", "GEN5"],
    },
  },
  tch: {
    "TCH-A": {
      title: "TCH-A · Teaching Context",
      subtitle: "4 câu",
      color: "#0F6E56",
      bg: "#E1F5EE",
      keys: ["TCH-A1", "TCH-A2", "TCH-A3", "TCH-A4"],
    },
    "TCH-B": {
      title: "TCH-B · LMS Expectations",
      subtitle: "5 câu",
      color: "#0F6E56",
      bg: "#E1F5EE",
      keys: ["TCH-B1", "TCH-B2", "TCH-B3", "TCH-B4", "TCH-B5"],
    },
  },
  par: {
    "PAR-A": {
      title: "PAR-A · Family Context",
      subtitle: "2 câu",
      color: "#993C1D",
      bg: "#FAECE7",
      keys: ["PAR-A1", "PAR-A2"],
    },
    "PAR-B": {
      title: "PAR-B · Expectations & Budget",
      subtitle: "3 câu",
      color: "#993C1D",
      bg: "#FAECE7",
      keys: ["PAR-B1", "PAR-B4", "PAR-B5"],
    },
  },
  cns: {
    "CNS-A": {
      title: "CNS-A · Counselor Context",
      subtitle: "1 câu",
      color: "#185FA5",
      bg: "#E6F1FB",
      keys: ["CNS-A2"],
    },
    "CNS-B": {
      title: "CNS-B · Partnership & Portal",
      subtitle: "3 câu",
      color: "#185FA5",
      bg: "#E6F1FB",
      keys: ["CNS-B2", "CNS-B3", "CNS-B4"],
    },
  },
  clt: {
    "CLT-A": {
      title: "CLT-A · Institutional Context",
      subtitle: "2 câu",
      color: "#854F0B",
      bg: "#FAEEDA",
      keys: ["CLT-A1", "CLT-A4"],
    },
    "CLT-B": {
      title: "CLT-B · Standards & Collaboration",
      subtitle: "3 câu",
      color: "#854F0B",
      bg: "#FAEEDA",
      keys: ["CLT-B1", "CLT-B4", "CLT-B5"],
    },
  },
};

export function getQuestionsForSection(
  groupKey: string,
  sectionKey: string
): QuestionDef[] {
  const section = SECTIONS[groupKey]?.[sectionKey];
  if (!section) return [];
  return section.keys
    .map((key) => QUESTIONS[key])
    .filter((q): q is QuestionDef => !!q);
}

export function getSectionKeys(groupKey: string): string[] {
  return Object.keys(SECTIONS[groupKey] || {});
}
